Description: Deploy ACM for my domain

Parameters: 
  r53ZoneId:
    Type: String
  owner:
    Type: String
  ownerEmail:
    Type: String
  enrironment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
      - test

Resources: 
  cert0:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: leonardobozcaitano.com
      DomainValidationOptions:
        - DomainName: www.leonardobozcaitano.com
          HostedZoneId: !Ref r53ZoneId
      ValidationMethod: DNS
      Tags:
        - Key: owner
          Value: !Ref owner
        - Key: ownerEmail
          Value: !Ref ownerEmail
        - Key: enrironment
          Value: !Ref enrironment

Outputs:
  cert0:
    Value: !Ref cert0
    Export:
      Name: !Sub '${AWS::StackName}-arn'