Description: Deploy the Cloudfront for s3 static website

Parameters: 
  s3Stack: 
    Type: String
    Default: personal-website-s3
  acmStack: 
    Type: String
    Default: personal-website-acm
  owner:
    Type: String
  ownerEmail:
    Type: String
  environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
      - test
      
Resources:
  cloudfrontDistribution: 
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Personal website Distribution
        DefaultCacheBehavior: 
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: PersonalWebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https 
        Enabled: true
        Origins: 
          - DomainName: {'Fn::ImportValue': !Sub '${s3Stack}-domain'}
            Id: PersonalWebsiteOrigin
            S3OriginConfig: 
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', {'Fn::ImportValue': !Sub '${s3Stack}-oai'}]]
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: {'Fn::ImportValue': !Sub '${acmStack}-arn'}
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only  
      Tags:
        - Key: owner
          Value: !Ref owner
        - Key: ownerEmail
          Value: !Ref ownerEmail
        - Key: environment
          Value: !Ref environment