name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy ACM Cloudformation Template
      run: aws cloudformation deploy --template-file ./acm.yml --stack-name personal-website-stack --parameter-overrides r53ZoneId=${{ secrets.AWS_R53_HOSTED_ZONE_ID }} owner=${{ secrets.AWS_CERTIFICATE_OWNER }} ownerEmail=${{ secrets.AWS_CERTIFICATE_OWNER_EMAIL }} enrironment=production
              
    - name: Deploy S3 Cloudformation Template
      run: aws cloudformation deploy --template-file ./s3.yml --stack-name personal-website-stack --parameter-overrides owner=${{ secrets.AWS_CERTIFICATE_OWNER }} ownerEmail=${{ secrets.AWS_CERTIFICATE_OWNER_EMAIL }} enrironment=production
